using CheckMate.Domain.Entities;

namespace CheckMate.Infrastructure.Persistence.SeedData;

public static class CountrySeedData
{
    // Source: https://countrycode.org/ (2026-09-19).
    // Names and ordering are preserved from the source; each dialing code has a + prefix.
    // Keep existing IDs stable when adding or updating entries.
    public static Country[] GetCountries() =>
    [
        new Country { CountryId = 1, CountryName = "Afghanistan", PhoneDialCode = "+93" },
        new Country { CountryId = 2, CountryName = "Albania", PhoneDialCode = "+355" },
        new Country { CountryId = 3, CountryName = "Algeria", PhoneDialCode = "+213" },
        new Country { CountryId = 4, CountryName = "American Samoa", PhoneDialCode = "+1-684" },
        new Country { CountryId = 5, CountryName = "Andorra", PhoneDialCode = "+376" },
        new Country { CountryId = 6, CountryName = "Angola", PhoneDialCode = "+244" },
        new Country { CountryId = 7, CountryName = "Anguilla", PhoneDialCode = "+1-264" },
        new Country { CountryId = 8, CountryName = "Antarctica", PhoneDialCode = "+672" },
        new Country { CountryId = 9, CountryName = "Antigua and Barbuda", PhoneDialCode = "+1-268" },
        new Country { CountryId = 10, CountryName = "Argentina", PhoneDialCode = "+54" },
        new Country { CountryId = 11, CountryName = "Armenia", PhoneDialCode = "+374" },
        new Country { CountryId = 12, CountryName = "Aruba", PhoneDialCode = "+297" },
        new Country { CountryId = 13, CountryName = "Australia", PhoneDialCode = "+61" },
        new Country { CountryId = 14, CountryName = "Austria", PhoneDialCode = "+43" },
        new Country { CountryId = 15, CountryName = "Azerbaijan", PhoneDialCode = "+994" },
        new Country { CountryId = 16, CountryName = "Bahamas", PhoneDialCode = "+1-242" },
        new Country { CountryId = 17, CountryName = "Bahrain", PhoneDialCode = "+973" },
        new Country { CountryId = 18, CountryName = "Bangladesh", PhoneDialCode = "+880" },
        new Country { CountryId = 19, CountryName = "Barbados", PhoneDialCode = "+1-246" },
        new Country { CountryId = 20, CountryName = "Belarus", PhoneDialCode = "+375" },
        new Country { CountryId = 21, CountryName = "Belgium", PhoneDialCode = "+32" },
        new Country { CountryId = 22, CountryName = "Belize", PhoneDialCode = "+501" },
        new Country { CountryId = 23, CountryName = "Benin", PhoneDialCode = "+229" },
        new Country { CountryId = 24, CountryName = "Bermuda", PhoneDialCode = "+1-441" },
        new Country { CountryId = 25, CountryName = "Bhutan", PhoneDialCode = "+975" },
        new Country { CountryId = 26, CountryName = "Bolivia", PhoneDialCode = "+591" },
        new Country { CountryId = 27, CountryName = "Bosnia and Herzegovina", PhoneDialCode = "+387" },
        new Country { CountryId = 28, CountryName = "Botswana", PhoneDialCode = "+267" },
        new Country { CountryId = 29, CountryName = "Brazil", PhoneDialCode = "+55" },
        new Country { CountryId = 30, CountryName = "British Indian Ocean Territory", PhoneDialCode = "+246" },
        new Country { CountryId = 31, CountryName = "British Virgin Islands", PhoneDialCode = "+1-284" },
        new Country { CountryId = 32, CountryName = "Brunei", PhoneDialCode = "+673" },
        new Country { CountryId = 33, CountryName = "Bulgaria", PhoneDialCode = "+359" },
        new Country { CountryId = 34, CountryName = "Burkina Faso", PhoneDialCode = "+226" },
        new Country { CountryId = 35, CountryName = "Burundi", PhoneDialCode = "+257" },
        new Country { CountryId = 36, CountryName = "Cambodia", PhoneDialCode = "+855" },
        new Country { CountryId = 37, CountryName = "Cameroon", PhoneDialCode = "+237" },
        new Country { CountryId = 38, CountryName = "Canada", PhoneDialCode = "+1" },
        new Country { CountryId = 39, CountryName = "Cape Verde", PhoneDialCode = "+238" },
        new Country { CountryId = 40, CountryName = "Cayman Islands", PhoneDialCode = "+1-345" },
        new Country { CountryId = 41, CountryName = "Central African Republic", PhoneDialCode = "+236" },
        new Country { CountryId = 42, CountryName = "Chad", PhoneDialCode = "+235" },
        new Country { CountryId = 43, CountryName = "Chile", PhoneDialCode = "+56" },
        new Country { CountryId = 44, CountryName = "China", PhoneDialCode = "+86" },
        new Country { CountryId = 45, CountryName = "Christmas Island", PhoneDialCode = "+61" },
        new Country { CountryId = 46, CountryName = "Cocos Islands", PhoneDialCode = "+61" },
        new Country { CountryId = 47, CountryName = "Colombia", PhoneDialCode = "+57" },
        new Country { CountryId = 48, CountryName = "Comoros", PhoneDialCode = "+269" },
        new Country { CountryId = 49, CountryName = "Cook Islands", PhoneDialCode = "+682" },
        new Country { CountryId = 50, CountryName = "Costa Rica", PhoneDialCode = "+506" },
        new Country { CountryId = 51, CountryName = "Croatia", PhoneDialCode = "+385" },
        new Country { CountryId = 52, CountryName = "Cuba", PhoneDialCode = "+53" },
        new Country { CountryId = 53, CountryName = "Curacao", PhoneDialCode = "+599" },
        new Country { CountryId = 54, CountryName = "Cyprus", PhoneDialCode = "+357" },
        new Country { CountryId = 55, CountryName = "Czech Republic", PhoneDialCode = "+420" },
        new Country { CountryId = 56, CountryName = "Democratic Republic of the Congo", PhoneDialCode = "+243" },
        new Country { CountryId = 57, CountryName = "Denmark", PhoneDialCode = "+45" },
        new Country { CountryId = 58, CountryName = "Djibouti", PhoneDialCode = "+253" },
        new Country { CountryId = 59, CountryName = "Dominica", PhoneDialCode = "+1-767" },
        new Country { CountryId = 60, CountryName = "Dominican Republic", PhoneDialCode = "+1-809, +1-829, +1-849" },
        new Country { CountryId = 61, CountryName = "East Timor", PhoneDialCode = "+670" },
        new Country { CountryId = 62, CountryName = "Ecuador", PhoneDialCode = "+593" },
        new Country { CountryId = 63, CountryName = "Egypt", PhoneDialCode = "+20" },
        new Country { CountryId = 64, CountryName = "El Salvador", PhoneDialCode = "+503" },
        new Country { CountryId = 65, CountryName = "Equatorial Guinea", PhoneDialCode = "+240" },
        new Country { CountryId = 66, CountryName = "Eritrea", PhoneDialCode = "+291" },
        new Country { CountryId = 67, CountryName = "Estonia", PhoneDialCode = "+372" },
        new Country { CountryId = 68, CountryName = "Ethiopia", PhoneDialCode = "+251" },
        new Country { CountryId = 69, CountryName = "Falkland Islands", PhoneDialCode = "+500" },
        new Country { CountryId = 70, CountryName = "Faroe Islands", PhoneDialCode = "+298" },
        new Country { CountryId = 71, CountryName = "Fiji", PhoneDialCode = "+679" },
        new Country { CountryId = 72, CountryName = "Finland", PhoneDialCode = "+358" },
        new Country { CountryId = 73, CountryName = "France", PhoneDialCode = "+33" },
        new Country { CountryId = 74, CountryName = "French Polynesia", PhoneDialCode = "+689" },
        new Country { CountryId = 75, CountryName = "Gabon", PhoneDialCode = "+241" },
        new Country { CountryId = 76, CountryName = "Gambia", PhoneDialCode = "+220" },
        new Country { CountryId = 77, CountryName = "Georgia", PhoneDialCode = "+995" },
        new Country { CountryId = 78, CountryName = "Germany", PhoneDialCode = "+49" },
        new Country { CountryId = 79, CountryName = "Ghana", PhoneDialCode = "+233" },
        new Country { CountryId = 80, CountryName = "Gibraltar", PhoneDialCode = "+350" },
        new Country { CountryId = 81, CountryName = "Greece", PhoneDialCode = "+30" },
        new Country { CountryId = 82, CountryName = "Greenland", PhoneDialCode = "+299" },
        new Country { CountryId = 83, CountryName = "Grenada", PhoneDialCode = "+1-473" },
        new Country { CountryId = 84, CountryName = "Guam", PhoneDialCode = "+1-671" },
        new Country { CountryId = 85, CountryName = "Guatemala", PhoneDialCode = "+502" },
        new Country { CountryId = 86, CountryName = "Guernsey", PhoneDialCode = "+44-1481" },
        new Country { CountryId = 87, CountryName = "Guinea", PhoneDialCode = "+224" },
        new Country { CountryId = 88, CountryName = "Guinea-Bissau", PhoneDialCode = "+245" },
        new Country { CountryId = 89, CountryName = "Guyana", PhoneDialCode = "+592" },
        new Country { CountryId = 90, CountryName = "Haiti", PhoneDialCode = "+509" },
        new Country { CountryId = 91, CountryName = "Honduras", PhoneDialCode = "+504" },
        new Country { CountryId = 92, CountryName = "Hong Kong", PhoneDialCode = "+852" },
        new Country { CountryId = 93, CountryName = "Hungary", PhoneDialCode = "+36" },
        new Country { CountryId = 94, CountryName = "Iceland", PhoneDialCode = "+354" },
        new Country { CountryId = 95, CountryName = "India", PhoneDialCode = "+91" },
        new Country { CountryId = 96, CountryName = "Indonesia", PhoneDialCode = "+62" },
        new Country { CountryId = 97, CountryName = "Iran", PhoneDialCode = "+98" },
        new Country { CountryId = 98, CountryName = "Iraq", PhoneDialCode = "+964" },
        new Country { CountryId = 99, CountryName = "Ireland", PhoneDialCode = "+353" },
        new Country { CountryId = 100, CountryName = "Isle of Man", PhoneDialCode = "+44-1624" },
        new Country { CountryId = 101, CountryName = "Israel", PhoneDialCode = "+972" },
        new Country { CountryId = 102, CountryName = "Italy", PhoneDialCode = "+39" },
        new Country { CountryId = 103, CountryName = "Ivory Coast", PhoneDialCode = "+225" },
        new Country { CountryId = 104, CountryName = "Jamaica", PhoneDialCode = "+1-876" },
        new Country { CountryId = 105, CountryName = "Japan", PhoneDialCode = "+81" },
        new Country { CountryId = 106, CountryName = "Jersey", PhoneDialCode = "+44-1534" },
        new Country { CountryId = 107, CountryName = "Jordan", PhoneDialCode = "+962" },
        new Country { CountryId = 108, CountryName = "Kazakhstan", PhoneDialCode = "+7" },
        new Country { CountryId = 109, CountryName = "Kenya", PhoneDialCode = "+254" },
        new Country { CountryId = 110, CountryName = "Kiribati", PhoneDialCode = "+686" },
        new Country { CountryId = 111, CountryName = "Kosovo", PhoneDialCode = "+383" },
        new Country { CountryId = 112, CountryName = "Kuwait", PhoneDialCode = "+965" },
        new Country { CountryId = 113, CountryName = "Kyrgyzstan", PhoneDialCode = "+996" },
        new Country { CountryId = 114, CountryName = "Laos", PhoneDialCode = "+856" },
        new Country { CountryId = 115, CountryName = "Latvia", PhoneDialCode = "+371" },
        new Country { CountryId = 116, CountryName = "Lebanon", PhoneDialCode = "+961" },
        new Country { CountryId = 117, CountryName = "Lesotho", PhoneDialCode = "+266" },
        new Country { CountryId = 118, CountryName = "Liberia", PhoneDialCode = "+231" },
        new Country { CountryId = 119, CountryName = "Libya", PhoneDialCode = "+218" },
        new Country { CountryId = 120, CountryName = "Liechtenstein", PhoneDialCode = "+423" },
        new Country { CountryId = 121, CountryName = "Lithuania", PhoneDialCode = "+370" },
        new Country { CountryId = 122, CountryName = "Luxembourg", PhoneDialCode = "+352" },
        new Country { CountryId = 123, CountryName = "Macau", PhoneDialCode = "+853" },
        new Country { CountryId = 124, CountryName = "Macedonia", PhoneDialCode = "+389" },
        new Country { CountryId = 125, CountryName = "Madagascar", PhoneDialCode = "+261" },
        new Country { CountryId = 126, CountryName = "Malawi", PhoneDialCode = "+265" },
        new Country { CountryId = 127, CountryName = "Malaysia", PhoneDialCode = "+60" },
        new Country { CountryId = 128, CountryName = "Maldives", PhoneDialCode = "+960" },
        new Country { CountryId = 129, CountryName = "Mali", PhoneDialCode = "+223" },
        new Country { CountryId = 130, CountryName = "Malta", PhoneDialCode = "+356" },
        new Country { CountryId = 131, CountryName = "Marshall Islands", PhoneDialCode = "+692" },
        new Country { CountryId = 132, CountryName = "Mauritania", PhoneDialCode = "+222" },
        new Country { CountryId = 133, CountryName = "Mauritius", PhoneDialCode = "+230" },
        new Country { CountryId = 134, CountryName = "Mayotte", PhoneDialCode = "+262" },
        new Country { CountryId = 135, CountryName = "Mexico", PhoneDialCode = "+52" },
        new Country { CountryId = 136, CountryName = "Micronesia", PhoneDialCode = "+691" },
        new Country { CountryId = 137, CountryName = "Moldova", PhoneDialCode = "+373" },
        new Country { CountryId = 138, CountryName = "Monaco", PhoneDialCode = "+377" },
        new Country { CountryId = 139, CountryName = "Mongolia", PhoneDialCode = "+976" },
        new Country { CountryId = 140, CountryName = "Montenegro", PhoneDialCode = "+382" },
        new Country { CountryId = 141, CountryName = "Montserrat", PhoneDialCode = "+1-664" },
        new Country { CountryId = 142, CountryName = "Morocco", PhoneDialCode = "+212" },
        new Country { CountryId = 143, CountryName = "Mozambique", PhoneDialCode = "+258" },
        new Country { CountryId = 144, CountryName = "Myanmar", PhoneDialCode = "+95" },
        new Country { CountryId = 145, CountryName = "Namibia", PhoneDialCode = "+264" },
        new Country { CountryId = 146, CountryName = "Nauru", PhoneDialCode = "+674" },
        new Country { CountryId = 147, CountryName = "Nepal", PhoneDialCode = "+977" },
        new Country { CountryId = 148, CountryName = "Netherlands", PhoneDialCode = "+31" },
        new Country { CountryId = 149, CountryName = "Netherlands Antilles", PhoneDialCode = "+599" },
        new Country { CountryId = 150, CountryName = "New Caledonia", PhoneDialCode = "+687" },
        new Country { CountryId = 151, CountryName = "New Zealand", PhoneDialCode = "+64" },
        new Country { CountryId = 152, CountryName = "Nicaragua", PhoneDialCode = "+505" },
        new Country { CountryId = 153, CountryName = "Niger", PhoneDialCode = "+227" },
        new Country { CountryId = 154, CountryName = "Nigeria", PhoneDialCode = "+234" },
        new Country { CountryId = 155, CountryName = "Niue", PhoneDialCode = "+683" },
        new Country { CountryId = 156, CountryName = "North Korea", PhoneDialCode = "+850" },
        new Country { CountryId = 157, CountryName = "Northern Mariana Islands", PhoneDialCode = "+1-670" },
        new Country { CountryId = 158, CountryName = "Norway", PhoneDialCode = "+47" },
        new Country { CountryId = 159, CountryName = "Oman", PhoneDialCode = "+968" },
        new Country { CountryId = 160, CountryName = "Pakistan", PhoneDialCode = "+92" },
        new Country { CountryId = 161, CountryName = "Palau", PhoneDialCode = "+680" },
        new Country { CountryId = 162, CountryName = "Palestine", PhoneDialCode = "+970" },
        new Country { CountryId = 163, CountryName = "Panama", PhoneDialCode = "+507" },
        new Country { CountryId = 164, CountryName = "Papua New Guinea", PhoneDialCode = "+675" },
        new Country { CountryId = 165, CountryName = "Paraguay", PhoneDialCode = "+595" },
        new Country { CountryId = 166, CountryName = "Peru", PhoneDialCode = "+51" },
        new Country { CountryId = 167, CountryName = "Philippines", PhoneDialCode = "+63" },
        new Country { CountryId = 168, CountryName = "Pitcairn", PhoneDialCode = "+64" },
        new Country { CountryId = 169, CountryName = "Poland", PhoneDialCode = "+48" },
        new Country { CountryId = 170, CountryName = "Portugal", PhoneDialCode = "+351" },
        new Country { CountryId = 171, CountryName = "Puerto Rico", PhoneDialCode = "+1-787, +1-939" },
        new Country { CountryId = 172, CountryName = "Qatar", PhoneDialCode = "+974" },
        new Country { CountryId = 173, CountryName = "Republic of the Congo", PhoneDialCode = "+242" },
        new Country { CountryId = 174, CountryName = "Reunion", PhoneDialCode = "+262" },
        new Country { CountryId = 175, CountryName = "Romania", PhoneDialCode = "+40" },
        new Country { CountryId = 176, CountryName = "Russia", PhoneDialCode = "+7" },
        new Country { CountryId = 177, CountryName = "Rwanda", PhoneDialCode = "+250" },
        new Country { CountryId = 178, CountryName = "Saint Barthelemy", PhoneDialCode = "+590" },
        new Country { CountryId = 179, CountryName = "Saint Helena", PhoneDialCode = "+290" },
        new Country { CountryId = 180, CountryName = "Saint Kitts and Nevis", PhoneDialCode = "+1-869" },
        new Country { CountryId = 181, CountryName = "Saint Lucia", PhoneDialCode = "+1-758" },
        new Country { CountryId = 182, CountryName = "Saint Martin", PhoneDialCode = "+590" },
        new Country { CountryId = 183, CountryName = "Saint Pierre and Miquelon", PhoneDialCode = "+508" },
        new Country { CountryId = 184, CountryName = "Saint Vincent and the Grenadines", PhoneDialCode = "+1-784" },
        new Country { CountryId = 185, CountryName = "Samoa", PhoneDialCode = "+685" },
        new Country { CountryId = 186, CountryName = "San Marino", PhoneDialCode = "+378" },
        new Country { CountryId = 187, CountryName = "Sao Tome and Principe", PhoneDialCode = "+239" },
        new Country { CountryId = 188, CountryName = "Saudi Arabia", PhoneDialCode = "+966" },
        new Country { CountryId = 189, CountryName = "Senegal", PhoneDialCode = "+221" },
        new Country { CountryId = 190, CountryName = "Serbia", PhoneDialCode = "+381" },
        new Country { CountryId = 191, CountryName = "Seychelles", PhoneDialCode = "+248" },
        new Country { CountryId = 192, CountryName = "Sierra Leone", PhoneDialCode = "+232" },
        new Country { CountryId = 193, CountryName = "Singapore", PhoneDialCode = "+65" },
        new Country { CountryId = 194, CountryName = "Sint Maarten", PhoneDialCode = "+1-721" },
        new Country { CountryId = 195, CountryName = "Slovakia", PhoneDialCode = "+421" },
        new Country { CountryId = 196, CountryName = "Slovenia", PhoneDialCode = "+386" },
        new Country { CountryId = 197, CountryName = "Solomon Islands", PhoneDialCode = "+677" },
        new Country { CountryId = 198, CountryName = "Somalia", PhoneDialCode = "+252" },
        new Country { CountryId = 199, CountryName = "South Africa", PhoneDialCode = "+27" },
        new Country { CountryId = 200, CountryName = "South Korea", PhoneDialCode = "+82" },
        new Country { CountryId = 201, CountryName = "South Sudan", PhoneDialCode = "+211" },
        new Country { CountryId = 202, CountryName = "Spain", PhoneDialCode = "+34" },
        new Country { CountryId = 203, CountryName = "Sri Lanka", PhoneDialCode = "+94" },
        new Country { CountryId = 204, CountryName = "Sudan", PhoneDialCode = "+249" },
        new Country { CountryId = 205, CountryName = "Suriname", PhoneDialCode = "+597" },
        new Country { CountryId = 206, CountryName = "Svalbard and Jan Mayen", PhoneDialCode = "+47" },
        new Country { CountryId = 207, CountryName = "Swaziland", PhoneDialCode = "+268" },
        new Country { CountryId = 208, CountryName = "Sweden", PhoneDialCode = "+46" },
        new Country { CountryId = 209, CountryName = "Switzerland", PhoneDialCode = "+41" },
        new Country { CountryId = 210, CountryName = "Syria", PhoneDialCode = "+963" },
        new Country { CountryId = 211, CountryName = "Taiwan", PhoneDialCode = "+886" },
        new Country { CountryId = 212, CountryName = "Tajikistan", PhoneDialCode = "+992" },
        new Country { CountryId = 213, CountryName = "Tanzania", PhoneDialCode = "+255" },
        new Country { CountryId = 214, CountryName = "Thailand", PhoneDialCode = "+66" },
        new Country { CountryId = 215, CountryName = "Togo", PhoneDialCode = "+228" },
        new Country { CountryId = 216, CountryName = "Tokelau", PhoneDialCode = "+690" },
        new Country { CountryId = 217, CountryName = "Tonga", PhoneDialCode = "+676" },
        new Country { CountryId = 218, CountryName = "Trinidad and Tobago", PhoneDialCode = "+1-868" },
        new Country { CountryId = 219, CountryName = "Tunisia", PhoneDialCode = "+216" },
        new Country { CountryId = 220, CountryName = "Turkey", PhoneDialCode = "+90" },
        new Country { CountryId = 221, CountryName = "Turkmenistan", PhoneDialCode = "+993" },
        new Country { CountryId = 222, CountryName = "Turks and Caicos Islands", PhoneDialCode = "+1-649" },
        new Country { CountryId = 223, CountryName = "Tuvalu", PhoneDialCode = "+688" },
        new Country { CountryId = 224, CountryName = "U.S. Virgin Islands", PhoneDialCode = "+1-340" },
        new Country { CountryId = 225, CountryName = "Uganda", PhoneDialCode = "+256" },
        new Country { CountryId = 226, CountryName = "Ukraine", PhoneDialCode = "+380" },
        new Country { CountryId = 227, CountryName = "United Arab Emirates", PhoneDialCode = "+971" },
        new Country { CountryId = 228, CountryName = "United Kingdom", PhoneDialCode = "+44" },
        new Country { CountryId = 229, CountryName = "United States", PhoneDialCode = "+1" },
        new Country { CountryId = 230, CountryName = "Uruguay", PhoneDialCode = "+598" },
        new Country { CountryId = 231, CountryName = "Uzbekistan", PhoneDialCode = "+998" },
        new Country { CountryId = 232, CountryName = "Vanuatu", PhoneDialCode = "+678" },
        new Country { CountryId = 233, CountryName = "Vatican", PhoneDialCode = "+379" },
        new Country { CountryId = 234, CountryName = "Venezuela", PhoneDialCode = "+58" },
        new Country { CountryId = 235, CountryName = "Vietnam", PhoneDialCode = "+84" },
        new Country { CountryId = 236, CountryName = "Wallis and Futuna", PhoneDialCode = "+681" },
        new Country { CountryId = 237, CountryName = "Western Sahara", PhoneDialCode = "+212" },
        new Country { CountryId = 238, CountryName = "Yemen", PhoneDialCode = "+967" },
        new Country { CountryId = 239, CountryName = "Zambia", PhoneDialCode = "+260" },
        new Country { CountryId = 240, CountryName = "Zimbabwe", PhoneDialCode = "+263" },
    ];
}
